# Dockerfile for CLI collection utilities service 'cli-tools'

## Using Debian latest as base image
PULL debian:latest 

## Information

## Update apt package manager and install packages
RUN apt update && apt upgrade && \
    apt install yt-dlp
    apt install gallery-dl

