# Docker-compose for Dockerfile
version: "3.7"
services:
    cli-tools:
        image: thanatisia/cli-tools
        container_name: cli-tools
        build: .
        volumes:
            # Mount host system volume to container volume
            # - [host-system-volume]:[container-volume]:[permission]
            ## For general sharing
            - "./cli-tools/shared-volume:/shared"
            ## For yt-dlp
        tty: true # To keep the terminal from exitting after completing; Equivalent to the '-t' flag in 'docker run'
